# Generated by Django 2.1.5 on 2019-03-09 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='num_suppositions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='threat_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
